export enum NotificationType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_REMINDER_24H = 'BOOKING_REMINDER_24H',
  BOOKING_REMINDER_2H = 'BOOKING_REMINDER_2H',
  STATUS_CHANGED = 'STATUS_CHANGED',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
}
